### ISSUE TITLE
module 'numpy' has no attribute 'int'.

### ISSUE THREAD

**Issue by ShannonTown** [tpecot/DeepLearningForBiologists_FromClassificationToSegmentation#4]
Hi, I was not able to use the Stardist Training2D script locally using my GPU as mentioned in another issue #2 (I did try to use it with CPU, it worked but much slower), so I tried to use the colab version of Training2D, and ran into the error: module 'numpy' has no attribute 'int'.

Here is a screenshot of more details:
![image](https://github.com/tpecot/DeepLearningForBiologists_FromClassificationToSegmentation/assets/30399381/0365496a-58cc-4510-a40c-379a40e601ce)

I tried to downgrade the tensorflow and numpy version but it can't go prior to tensorflow 2.8.0 and numpy 1.20.0 in colab. I was wondering if this issue can be fixed in your package or if I should go to the github page of stardist since it seems to be related to a line in the stardist scripts.

Thank you!

**Comment by tpecot** [comment]
Hi again! Colab environment is always evolving. As I don't use it on a regular basis, I only go back to it when I do the training. It is possible that it currently does not work with the code that is available. I'll change it when I do again the training.

On a more general note, I wrote these programs and did the videos to offer the possibility to the people that attend my training to do it and get back to it. Although it is useful to other people, and I'm glad to see that you seem to find it useful, I do not have time to answer every single problem encountered by people using them. However, I hope you have learnt useful information that will be of great interest for your studies.
